name: 'Nested Vault Action'
description: 'A Nested Vault Action to be used in E2E tests'
runs:
  using: "composite"
  steps:
    - uses: ./
      with:
        url: http://localhost:8200
        token: testtoken
        secrets: |
          secret/data/nested-vault-action secret | NESTED_VAULT_ACTION_SECRET;