# This is a sample workflow to help test contributions
# Change the branch name, url and token to fit with your own environment

# To run this locally with act use:
#     act workflow_dispatch -j local-test
#
# If you have permissions, you can run this workflow via the GitHub UI.
# Otherwise, use 'on: push' instead of 'on: workflow_dispatch'.

# Don't forget to revert the file changes and invalidate any tokens that were
# committed before opening a pull request.
on: workflow_dispatch

name: local-test

jobs:
  local-test:
    name: local-test
    runs-on: ubuntu-latest
    steps:
      - name: Import Secrets
        uses: hashicorp/vault-action@YOUR_BRANCH_NAME
        with:
          url: http://localhost:8200
          method: token
          token: testtoken
          secrets: |
            secret/data/test secret | SAMPLE_SECRET;
